# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92deaf990d469ba8dc53f448484ed9cb56be18e82aaca5c46a490da5aaff95456cd7b154b87547fe14fed42c63a5a00a28acfbf4e396eb6c2a8ce14a1202bfe

test:
  secret_key_base: ea0e996495309afdc1b49112e081b10fd9baa885099a94a14f228bc7a2556c6c633f96132c8e056bd61dccdd32dad7d6db34e000fa85e58d1355d8c426f9df84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
